// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using DocumentManagementApp.Data;



#nullable disable

namespace DocumentLibrary2.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230523214706_SaSTokennotnull")]
    partial class SaSTokennotnull : Migration

    {
protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<string>(
                name: "SasToken",
                table: "Documents",
                type: "text",
                nullable: true);

            migrationBuilder.Sql("UPDATE \"Documents\" SET \"SasToken\" = ''");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "SasToken",
                table: "Documents");
        }
    }
}
